server:
  port: 8080
  servlet:
    context-path: /ali-education
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
    username: root
    password: jia19971210
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.stackoverflow.dream.pojo
  configuration:
    useGeneratedKeys: true
    mapUnderscoreToCamelCase: true

logging:
  level:
    root: info
    com.stackoverflow.dream: debug
    org.springframework: WARN